apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: buildkit-rootless-pvc-build-
spec:
  entrypoint: buildkit-rootless-build-flow

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  volumes:
  - name: buildkitd
    emptyDir: {}

  templates:
  - name: buildkit-rootless-build-flow
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: buildkit-build
          template: buildkit-rootless

  - name: git-clone
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          set -eu
          git clone --branch master https://github.com/teaching-on-testbeds/gourmetgram.git /mnt/workspace
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: buildkit-rootless
    container:
      image: moby/buildkit:rootless
      env:
      - name: BUILDKITD_FLAGS
        value: --oci-worker-no-process-sandbox
      command: [buildctl-daemonless.sh]
      args:
        - build
        - --frontend
        - dockerfile.v0
        - --local
        - context=/mnt/workspace
        - --local
        - dockerfile=/mnt/workspace
        - --output
        - 'type=image,"name=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:staging-1.0.0,registry.kube-system.svc.cluster.local:5000/gourmetgram-app:canary-1.0.0,registry.kube-system.svc.cluster.local:5000/gourmetgram-app:production-1.0.0",push=true,registry.insecure=true'
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: Unconfined
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace
      - name: buildkitd
        mountPath: /home/user/.local/share/buildkit
