apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: revert-model
spec:
  entrypoint: revert-flow
  arguments:
    parameters:
    - name: environment
      value: "staging"
    - name: failed-model-version
    - name: failure-reason
      value: "Tests failed"

  templates:
  - name: revert-flow
    steps:
      # Step 1: Find previous version from MLFlow model history for this environment
      - - name: get-previous-version
          template: find-previous-version
          arguments:
            parameters:
            - name: failed-version
              value: "{{workflow.parameters.failed-model-version}}"
            - name: environment
              value: "{{workflow.parameters.environment}}"

      # Step 2: Verify previous container image exists using skopeo
      - - name: verify-previous-image
          template: skopeo-verify
          arguments:
            parameters:
            - name: previous-version
              value: "{{steps.get-previous-version.outputs.result}}"
            - name: environment
              value: "{{workflow.parameters.environment}}"

      # Step 3: Deploy previous version to environment
      - - name: deploy-previous
          template: trigger-deploy
          arguments:
            parameters:
            - name: model-version
              value: "{{steps.get-previous-version.outputs.result}}"
            - name: environment
              value: "{{workflow.parameters.environment}}"

      # Step 4: Update MLFlow alias to point back to previous version
      - - name: update-mlflow-alias
          template: set-mlflow-alias
          arguments:
            parameters:
            - name: model-version
              value: "{{steps.get-previous-version.outputs.result}}"
            - name: environment
              value: "{{workflow.parameters.environment}}"

      # Step 5: Log failure for debugging
      - - name: log-failure
          template: log-revert-reason
          arguments:
            parameters:
            - name: failed-version
              value: "{{workflow.parameters.failed-model-version}}"
            - name: reverted-to-version
              value: "{{steps.get-previous-version.outputs.result}}"
            - name: reason
              value: "{{workflow.parameters.failure-reason}}"
            - name: environment
              value: "{{workflow.parameters.environment}}"

  # Template: Find previous version from MLFlow for the given environment
  - name: find-previous-version
    inputs:
      parameters:
      - name: failed-version
      - name: environment
    script:
      image: python:3.11-slim
      command: [sh, -c]
      source: |
        pip install mlflow-skinny > /dev/null
        export MLFLOW_TRACKING_URI=http://mlflow.gourmetgram-platform.svc.cluster.local:8000

        python << 'EOF'
        import mlflow
        import sys

        client = mlflow.tracking.MlflowClient()
        failed_version = "{{inputs.parameters.failed-version}}"
        environment = "{{inputs.parameters.environment}}"
        model_name = "GourmetGramFood11Model"

        # First, try to find the last version that was successfully approved for this environment
        approved_alias = f"{environment}-approved"
        
        try:
            # Get all versions of the model
            versions = client.search_model_versions(f"name='{model_name}'")
            
            # Find the version with the {environment}-approved alias
            previous_version = None
            for v in versions:
                if v.aliases and approved_alias in v.aliases:
                    previous_version = v.version
                    print(f"Found last approved {environment} version: {previous_version}", file=sys.stderr)
                    print(f"This version previously passed all {environment} tests", file=sys.stderr)
                    break
            
            if previous_version is None:
                # Fallback: No approved version exists yet (first deployment scenario)
                # Find the highest version number less than the failed version
                print(f"WARNING: No '{approved_alias}' alias found", file=sys.stderr)
                print(f"Falling back to numerically previous version", file=sys.stderr)
                
                versions_sorted = sorted(versions, key=lambda v: int(v.version), reverse=True)
                failed_version_int = int(failed_version)
                
                for v in versions_sorted:
                    v_int = int(v.version)
                    if v_int < failed_version_int:
                        previous_version = v.version
                        break
                
                if previous_version is None:
                    print(f"ERROR: No previous version found before version {failed_version}", file=sys.stderr)
                    print("Cannot revert - this is the first version", file=sys.stderr)
                    exit(1)
                    
                print(f"Found fallback version: {previous_version}", file=sys.stderr)
            
            print(previous_version)
            
        except Exception as e:
            print(f"ERROR: Failed to find previous version: {e}", file=sys.stderr)
            exit(1)
        EOF

  # Template: Verify previous container image exists using skopeo
  - name: skopeo-verify
    inputs:
      parameters:
      - name: previous-version
      - name: environment
    container:
      image: quay.io/skopeo/stable
      command: [sh, -c]
      args:
        - |
          ENV="{{inputs.parameters.environment}}"
          TAG="${ENV}-1.0.{{inputs.parameters.previous-version}}"
          
          echo "Verifying previous ${ENV} image exists: ${TAG}"

          # Inspect the previous image to verify it exists in the registry
          # This will fail fast with a clear error if the image is missing
          skopeo inspect \
            --tls-verify=false \
            docker://registry.kube-system.svc.cluster.local:5000/gourmetgram-app:${TAG}

          echo "✓ Previous ${ENV} image verified: ${TAG}"
          echo "Ready to revert ${ENV} to this version"

  # Template: Update MLFlow alias to previous version
  - name: set-mlflow-alias
    inputs:
      parameters:
      - name: model-version
      - name: environment
    script:
      image: python:3.11-slim
      command: [sh, -c]
      source: |
        pip install mlflow-skinny > /dev/null
        export MLFLOW_TRACKING_URI=http://mlflow.gourmetgram-platform.svc.cluster.local:8000

        python -c "import mlflow; client = mlflow.tracking.MlflowClient(); client.set_registered_model_alias(name='GourmetGramFood11Model', alias='{{inputs.parameters.environment}}', version='{{inputs.parameters.model-version}}')"

        echo "Updated MLFlow {{inputs.parameters.environment}} alias to version {{inputs.parameters.model-version}}"

  # Template: Trigger deploy-container-image workflow
  - name: trigger-deploy
    inputs:
      parameters:
      - name: model-version
      - name: environment
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: deploy-container-image-
        spec:
          workflowTemplateRef:
            name: deploy-container-image
          arguments:
            parameters:
            - name: environment
              value: "{{inputs.parameters.environment}}"
            - name: model-version
              value: "{{inputs.parameters.model-version}}"

  # Template: Log revert reason for debugging
  - name: log-revert-reason
    inputs:
      parameters:
      - name: failed-version
      - name: reverted-to-version
      - name: reason
      - name: environment
    script:
      image: alpine:latest
      command: [sh]
      source: |
        #!/bin/sh
        ENV="{{inputs.parameters.environment}}"
        ENV_UPPER=$(echo "$ENV" | tr '[:lower:]' '[:upper:]')
        
        echo "=========================================="
        echo "${ENV_UPPER} REVERT PERFORMED"
        echo "=========================================="
        echo "Failed model version: {{inputs.parameters.failed-version}}"
        echo "Reverted to version: {{inputs.parameters.reverted-to-version}}"
        echo "Reason: {{inputs.parameters.reason}}"
        echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "=========================================="
        echo ""
        echo "Action items:"
        echo "1. Review test logs to identify failure cause"
        echo "2. Fix model/code issues before redeploying version {{inputs.parameters.failed-version}}"
        echo "3. ${ENV_UPPER} environment is now running version {{inputs.parameters.reverted-to-version}}"
        echo "=========================================="
